config/routes.rb
Sherpify::Application.routes.draw do
  match 'orders' => 'orders#index', :as => :orders
  match 'orders/:id/process' => 'orders#process_order', :as => :process_order

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :items, :class_name => 'OrderItem'

  def add(product)
    items << items.build(:product => product, :quantity => 1)
  end

  class << self
    def next_in_queue
      first
    end
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  validates_presence_of :order, :product, :quantity
end

app/models/order_processor.rb
class OrderProcessor
  attr_accessor :rules

  def initialize
    @rules = []
  end

  def process(order)
    result.success = false

    if @rules.length > 0
      @rules.each do |rule|
        if !rule.process(order, result)
          return result
        end
      end

      result.success = true
    end

    return result
  end

  private
    def result
      @result ||= ProcessorResult.new
    end
end

app/models/packing_slip.rb
class PackingSlip
  attr_accessor :type, :items

  def initialize
    @items = []
  end
end

app/models/processor_result.rb
class ProcessorResult
  attr_accessor :success, :packing_slips

  def initialize
    @success = false
    @packing_slips = []
  end
end

app/models/processor_rule.rb
class ProcessorRule
  def process(order, result)
    false
  end

  protected
    def packing_slip
      @slip ||= PackingSlip.new
    end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :price, :delivery

  def physical?
    if self.delivery == 'physical'
      return true
    else
      return false
    end
  end
end

app/models/rules.rb
module Rules
end

app/models/rules/membership_notification.rb
class Rules::MembershipNotification < ProcessorRule
  def process(order, result)
    items = order.items.select{ |i| i.product.kind == 'membership' }
    if items.length > 0
      items.each do |item|
        notifications.membership(item.product.owner, [item]).deliver
      end
    end

    return true
  end

  private
    def notifications
      Notifications
    end
end

app/models/rules/royalty_packing_slip.rb
class Rules::RoyaltyPackingSlip < ProcessorRule
  def process(order, result)
    items = order.items.select{ |i| i.product.kind == 'book' }

    if items.length > 0
      packing_slip.type = :royalties

      items.each do |item|
        packing_slip.items << item
      end

      result.packing_slips << packing_slip
    end

    return true
  end
end

app/models/rules/shipping_packing_slip.rb
class Rules::ShippingPackingSlip < ProcessorRule
  def process(order, result)
    items = order.items.select{ |i| i.product.physical? }

    if items.length > 0
      packing_slip.type = :shipping

      items.each do |item|
        packing_slip.items << item
      end

      result.packing_slips << packing_slip
    end

    return true
  end

  private
    def packing_slip
      @slip ||= PackingSlip.new
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @order = orders.next_in_queue
  end

  def process_order
    order = orders.find(params[:id])
    result = processor.process(order)

    if result.success
      @packing_slips = result.packing_slips

      flash[:notice] = 'Order processed successfully!'
    end
  end

  private
    def orders
      Order
    end

    def processor
      if @processor.nil?
        @processor = OrderProcessor.new
        @processor.rules.concat(rules)
      end

      @processor
    end

    def rules
      [
        Rules::ShippingPackingSlip.new,
        Rules::RoyaltyPackingSlip.new,
        Rules::MembershipNotification.new
      ]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sherpify</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/notifications/membership.text.erb
<% @items.each do |item| %>
  (<%=item.quantity%>) - <%=item.product.name%>
<% end %>

app/views/orders/index.html.erb
<%= form_for @order, :url => process_order_path(@order) do |f| -%>
  <%= f.submit "Process", :id => 'process' %>
<% end -%>

app/views/orders/process_order.html.erb
<%= render :partial => 'shared/packing_slips', :locals => { :packing_slips => @packing_slips } %>

app/views/shared/_messages.html.erb
<div id="messages">
<% [:notice, :warning, :message].each do |name| %>
    <% if flash[name] %>
      <div class="<%=name%>"><%=flash[name]%></div>
    <% end %>
<% end %>
</div>

app/views/shared/_packing_slips.html.erb
<% if packing_slips && packing_slips.length > 0 %>
  <div id="packing-slips">
    <h2>Packing Slips</h2>

    <% packing_slips.each do|slip| %>
      <div class="<%=slip.type%>">
        <h3><%=slip.type.capitalize%></h3>
        <% slip.items.each do |item| %>
          <div class="item">
            (<%=item.quantity%>) - <%=item.product.name%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>